### ISSUE TITLE
ModuleNotFoundError: No module named 'papermill.preprocess'

### ISSUE THREAD

**Issue by drakesiard** [vatlab/sos-papermill#9]
I can reliably reproduce the following. From a fresh python3 virtual env:
```bash
$ pip install papermill
$ python -c 'import papermill'
```
This works and exits without error. Then:
```bash
$ pip install sos-papermill
$ python -c 'import papermill'
```
Now the command fails in `papermill_engines.register_entry_points()` with the `ModuleNotFoundError: No module named 'papermill.preprocess'`. The versions involved are:
```
$ pip freeze | grep papermill
papermill==2.1.1
sos-papermill==0.1.6
$ python --version
Python 3.7.5
```
Let me know if you need additional information to help reproduce this.

**Comment by BoPeng** [comment]
Sorry, not sure why I was not notified of this ticket. ...

**Comment by BoPeng** [comment]
https://github.com/nteract/papermill/commit/1fd6c2ff031b08dcbb3b5864429de54681a2838f

is when the preprocess module is renamed.

**Comment by BoPeng** [comment]
sos-papermill 0.2.0 is released.
